name: Reusable workflow example

on: push

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - id: step1
      - run: |
          echo "inputs.allowed_features: ${{ inputs.username }}"
          echo "env.INPUT_ALLOWED_FEATURES: ${{ env.INPUT_ALLOWED_FEATURES }}"
        shell: bash
  call-workflow-passing-data:
    uses: RahulVadisetty91/HelloWorld/.github/workflows/call-workflow.yml@main
    with:
      username: anvesh
