#Template Version 1.0.0

name: Publish to Artifactory

on:
  release:
    types: [published,edited]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    name: A job to test this action
    steps:    
    - uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "${{ github.repository }}"
        file: "${{ steps.vars.outputs.tag }}"
        target: "release-asset.zip"
        token: ${{ secrets.GITHUB_TOKEN }} 
    
    - name: Display download directory
      run: | 
          ls -R
          
    - name: Upoad Release asset to JFrog
      id: uploadToJFrog
      run: |
        export RELEASE_NAME=`curl -sSf -u "tilakkalyan@gmail.com:Itsme148!" \-X PUT \-T release-asset.zip \'https://itsme.jfrog.io/artifactory/default-maven-virtual/release-asset.zip'`
        echo "JFrog Status= ${jfrogStatus}"
        
        
        
        
